package com.fb.object;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class GooglePage {

	public static void main(String[] args) throws InterruptedException {
		// TODO Auto-generated method stub
		WebDriver driver; // TODO Auto-generated method stub
		 System.setProperty("webdriver.gecko.driver","E:/let/geckodriver.exe");
       // System.setProperty("webdriver.chrome.driver", "E:\\QE\\chromedriver.exe");
        driver = new FirefoxDriver();
        String URL = "https://www.google.com/intl/en_in/gmail/about/";
        driver.get(URL);
        driver.manage().window().maximize();
        driver.findElement(By.xpath("//a[contains(text(),'Sign In')]")).click();
        driver.findElement(By.name("identifier")).sendKeys("yadgirkerashwin202");
        driver.findElement(By.xpath("//div[@id='identifierNext']/content/span")).click();
        Thread.sleep(2000);
        driver.findElement(By.xpath("//div[@id='password']/div/div/div/input")).sendKeys("password");
       
        driver.findElement(By.xpath("//div[@id='passwordNext']/content/span")).click();
        Thread.sleep(5000);
        driver.findElement(By.xpath("//div[@id=':ir']/div/div")).click();
        Thread.sleep(2000);
        driver.findElement(By.name("to")).sendKeys("divyashivakumar.95@gmail.com");
        Thread.sleep(1000);
        driver.findElement(By.name("subjectbox")).sendKeys("Autogenerated mail");
        Thread.sleep(1000);
        driver.findElement(By.xpath("//td[2]/div[2]/div")).sendKeys("Hi Divya , This is an auto generated mail. ");
        Thread.sleep(1000);
        driver.findElement(By.xpath("//div[4]/table/tbody/tr/td/div/div[2]")).click();
        
        
        

	}

}
